2021-10-01 09:55:18,651 INFO    MainThread:4914 [wandb_setup.py:_flush():69] setting env: {}
2021-10-01 09:55:18,651 WARNING MainThread:4914 [wandb_setup.py:_flush():69] could not find program at train.py
2021-10-01 09:55:18,651 INFO    MainThread:4914 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-01 09:55:18,651 INFO    MainThread:4914 [wandb_init.py:_log_setup():348] Logging user logs to /home/bhuwan/Desktop/cat-dog/scripts/outputs/2021-10-01/09-55-16/wandb/run-20211001_095518-3brehq2e/logs/debug.log
2021-10-01 09:55:18,651 INFO    MainThread:4914 [wandb_init.py:_log_setup():349] Logging internal logs to /home/bhuwan/Desktop/cat-dog/scripts/outputs/2021-10-01/09-55-16/wandb/run-20211001_095518-3brehq2e/logs/debug-internal.log
2021-10-01 09:55:18,651 INFO    MainThread:4914 [wandb_init.py:init():381] calling init triggers
2021-10-01 09:55:18,651 INFO    MainThread:4914 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {'lr': 0.0003, 'base_filters': 32, 'epochs': 2}
2021-10-01 09:55:18,651 INFO    MainThread:4914 [wandb_init.py:init():430] starting backend
2021-10-01 09:55:18,651 INFO    MainThread:4914 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-01 09:55:18,675 INFO    MainThread:4914 [backend.py:ensure_launched():135] starting backend process...
2021-10-01 09:55:18,679 INFO    MainThread:4914 [backend.py:ensure_launched():139] started backend process with pid: 4969
2021-10-01 09:55:18,680 INFO    MainThread:4914 [wandb_init.py:init():435] backend started and connected
2021-10-01 09:55:18,681 INFO    MainThread:4914 [wandb_init.py:init():494] updated telemetry
2021-10-01 09:55:18,681 INFO    MainThread:4914 [wandb_init.py:init():517] communicating current version
2021-10-01 09:55:19,237 INFO    MainThread:4914 [wandb_init.py:init():522] got version response upgrade_message: "wandb version 0.12.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-01 09:55:19,237 INFO    MainThread:4914 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-10-01 09:55:19,566 INFO    MainThread:4914 [wandb_init.py:init():557] starting run threads in backend
2021-10-01 09:55:24,571 INFO    MainThread:4914 [wandb_run.py:_console_start():1605] atexit reg
2021-10-01 09:55:24,571 INFO    MainThread:4914 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-10-01 09:55:24,572 INFO    MainThread:4914 [wandb_run.py:_redirect():1484] Redirecting console.
2021-10-01 09:55:24,574 INFO    MainThread:4914 [wandb_run.py:_redirect():1540] Redirects installed.
2021-10-01 09:55:24,574 INFO    MainThread:4914 [wandb_init.py:init():582] run started, returning control to user process
2021-10-01 09:55:24,716 INFO    MainThread:4914 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 1
2021-10-01 09:55:24,716 INFO    MainThread:4914 [wandb_run.py:_restore():1547] restore
2021-10-01 09:55:27,590 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 646
  total_bytes: 646
}

2021-10-01 09:55:27,694 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 646
  total_bytes: 646
}

2021-10-01 09:55:27,950 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 646
  total_bytes: 646
}

2021-10-01 09:55:28,579 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 646
  total_bytes: 2257
}

2021-10-01 09:55:28,680 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 646
  total_bytes: 24316
}

2021-10-01 09:55:28,783 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 646
  total_bytes: 24316
}

2021-10-01 09:55:28,885 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 646
  total_bytes: 24316
}

2021-10-01 09:55:28,988 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24316
  total_bytes: 24316
}

2021-10-01 09:55:29,091 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24316
  total_bytes: 24316
}

2021-10-01 09:55:29,194 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24316
  total_bytes: 24316
}

2021-10-01 09:55:29,297 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24316
  total_bytes: 24316
}

2021-10-01 09:55:29,400 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24316
  total_bytes: 24316
}

2021-10-01 09:55:29,503 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24316
  total_bytes: 24316
}

2021-10-01 09:55:29,716 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24316
  total_bytes: 24316
}

2021-10-01 09:55:30,312 INFO    MainThread:4914 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24316
  total_bytes: 24316
}
local_info {
}

2021-10-01 09:55:32,623 INFO    MainThread:4914 [wandb_run.py:_show_files():1947] logging synced files
